name: Build Wheels

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build twine

      - name: Compile binary (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          gcc src/pyvcon/vcontacts/Vcontacts.c -o src/pyvcon/vcontacts/vcon -lm

      - name: Compile with cl (Windows - MSVC)
        if: runner.os == 'Windows'
        run: |
          cl /Fe:src\pyvcon\vcontacts\vcon.exe src\pyvcon\vcontacts\Vcontacts.c

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Rename wheel based on platform
        run: |
          python rename_whl.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
